[workspace]
resolver = "3"
members = ["crates/aris", "crates/aris-cli", "python"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["ImFeH2 <i@feh2.im>"]
license = "Apache-2.0"
repository = "https://github.com/ImFeH2/aris"
readme = "README.md"

[workspace.dependencies]
aris = { path = "crates/aris" }
